### PR TITLE
feat: add functions to get stations that are together

### PR DESCRIPTION
**Pull request by rhwood**
Since WMATA codes each station with multiple lines that do not share tracks as separate stations in their API, provide methods to get stations at the same location in an array.

This provides to functions:
- `together()` which gets the other stations at the same location
- `allTogether()` which appends the current station to the results of `together()`

The use case for these methods is to to get all nextTrain results for a single multi-platform station (Fort Totten, Gallery Pl-Chinatown, L'Enfant Plaze, or Metro Center) in a single API call.

### CODE REVIEW

**Comment by emma-k-alexandra** [comment]
I like this idea a lot, I've thought about adding more (train) platform-focused code into this package in the past. This seems like a great addition, but I'm not sure I'm a fan of this implementation. Looking into it now.

**Comment by rhwood** [comment]
I'm not a fan of the method signatures myself, but I couldn't think of anything better as I wrote this up. I thought of using "otherPlatforms" and "allPlatforms", but the WMATA API seems to suggest that someone using it who really wants to know the platform would use "group" to get that information, so I eventually went with "together" and "allTogether"

**Comment by emma-k-alexandra** [comment]
@rhwood An alternate implementation I like a bit better is present in #12. Let me know if it satisfies your requirements for this feature.

**Comment by rhwood** [comment]
#12 works for my purposes (since what I am really interested in is the `allTogether` var, but given that the WMATA API allows for two other stations to be together with another station (even if they don't use the API that way), I'm uncomfortable with the idea that the `together` var in #12 is `Station` and not `[Station]`.

BTW, I did figure out how eliminate the variable declaration in `allTogether` in this PR.

**Comment by emma-k-alexandra** [comment]
Looking at [WMATA's 2025 Initiatives](https://www.wmata.com/initiatives/strategic-plans/2025.cfm), there's no plans to expand Fort Totten, Chinatown, L'Enfant Plaza or Metro Center to include a 3rd platform. WMATA's API provides a `StationTogether2` field & `StationInformation` provides a [`secondStationTogether`](https://github.com/emma-k-alexandra/WMATA.swift/blob/master/Sources/WMATA/Rail/RailResponses.swift#L786) field to match, but that field is currently unused by WMATA.

Since this field is unused, I feel perfectly comfortable ignoring it to make the `together` value `Station?`. If WMATA decides to build a whole new platform for millions of dollars I will happily make a breaking change to the API for this field 😁

I think the optional value fits Swift's ergonomics much better than a single valued or empty array.

Merging #12

**Pull request closed without merging**
